// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgndltuyjqyjftgcqfgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnbmRsdHV5anF5amZ0Z2NxZmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxMDQxMjIsImV4cCI6MjA5OTY4MDEyMn0.R7Vmo3kqHvmRkm-CeBl_6BOqLXwOe4RpuYTAMXZ2ReY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});