// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);

    // TEMP AUDIT: log Authorization for Storage payments-bucket writes.
    try {
      const url = typeof input === 'string' ? input : input instanceof URL ? input.toString() : (input as Request).url;
      if (url && url.includes('/storage/v1/object/payments/')) {
        const authz = headers.get('Authorization');
        // eslint-disable-next-line no-console
        console.log('[storage-auth-audit] outbound storage fetch', {
          url,
          method: (init?.method) || (input instanceof Request ? input.method : 'GET'),
          hasAuthorization: !!authz,
          authorizationScheme: authz?.split(' ')[0] ?? null,
          authorizationIsPublishableKey: authz === `Bearer ${supabaseKey}`,
          authorizationTokenParts: authz?.startsWith('Bearer ') ? authz.slice(7).split('.').length : null,
          apikeyPresent: !!headers.get('apikey'),
        });
      }
    } catch {
      // ignore audit errors
    }

    return fetch(input, { ...init, headers });
  };
}



function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const runtimeEnv = typeof globalThis !== 'undefined'
    ? (globalThis as typeof globalThis & {
        __digitalNestRuntimeEnv?: Record<string, string>;
        process?: unknown;
      })
    : undefined;

  const viteEnv = import.meta.env as Record<string, string | undefined> | undefined;
  const processLike = runtimeEnv?.process && typeof runtimeEnv.process === 'object'
    ? runtimeEnv.process as { env?: Record<string, string | undefined> }
    : undefined;

  const SUPABASE_URL = viteEnv?.['VITE_SUPABASE_URL'] || runtimeEnv?.__digitalNestRuntimeEnv?.['SUPABASE_URL'] || processLike?.env?.['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = viteEnv?.['VITE_SUPABASE_PUBLISHABLE_KEY'] || runtimeEnv?.__digitalNestRuntimeEnv?.['SUPABASE_PUBLISHABLE_KEY'] || processLike?.env?.['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

